// src/ui/shortcuts/HyprlandBindsSync.cpp

#include "HyprlandBindsSync.h"

#include <algorithm>
#include <cctype>
#include <cerrno>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <utility>

namespace saf {

namespace fs = std::filesystem;

namespace {

constexpr const char *MARKER_BEGIN =
    "# >>> simpleautoframer: managed block — do not edit by hand <<<";
constexpr const char *MARKER_END =
    "# <<< simpleautoframer: end managed block >>>";

bool isHyprland() {
  if (std::getenv("HYPRLAND_INSTANCE_SIGNATURE"))
    return true;
  const char *desktop = std::getenv("XDG_CURRENT_DESKTOP");
  if (desktop && std::strstr(desktop, "Hyprland"))
    return true;
  return false;
}

fs::path hyprlandConfigPath() {
  const char *home = std::getenv("HOME");
  if (!home)
    return {};
  fs::path p = fs::path(home) / ".config" / "hypr" / "hyprland.conf";
  return p;
}

/// Translate "Ctrl+Alt+1" -> (mods="CTRL ALT", key="1") in Hyprland
/// bind-syntax. Returns (mods, key). Key may be empty if the accelerator
/// couldn't be parsed.
std::pair<std::string, std::string> splitAccel(const std::string &accel) {
  std::string mods, key, cur;
  auto flush = [&]() {
    if (cur.empty())
      return;
    std::string up = cur;
    std::transform(up.begin(), up.end(), up.begin(),
                   [](unsigned char c) { return std::toupper(c); });
    if (up == "CTRL" || up == "CONTROL" || up == "ALT" || up == "SHIFT" ||
        up == "SUPER" || up == "META" || up == "WIN") {
      if (!mods.empty())
        mods += ' ';
      mods += (up == "WIN" || up == "META") ? "SUPER" : up;
    } else {
      key = cur;
    }
    cur.clear();
  };
  for (char c : accel) {
    if (c == '+')
      flush();
    else
      cur.push_back(c);
  }
  flush();
  return {mods, key};
}

std::string buildManagedBlock(const std::vector<ShortcutDescriptor> &sc) {
  std::ostringstream os;
  os << MARKER_BEGIN << '\n';
  os << "# Generated by SimpleAutoFramer. Re-generated every time the app\n"
     << "# registers its global shortcuts with the portal. Maps each key\n"
     << "# combination to the portal's empty-app_id:<id> entry.\n";
  if (sc.empty()) {
    os << "# (no shortcuts defined in any profile)\n";
  }
  for (const auto &d : sc) {
    auto [mods, key] = splitAccel(d.defaultAccel);
    if (key.empty())
      continue;
    os << "bind = " << mods << ", " << key << ", global, :" << d.id << '\n';
  }
  os << MARKER_END << '\n';
  return os.str();
}

/// Replace the existing managed block (or append one) inside `original`.
/// If the existing block exactly matches `newBlock`, no change is made
/// (returned string equals input).
std::string updateManagedBlock(const std::string &original,
                               const std::string &newBlock) {
  auto begin = original.find(MARKER_BEGIN);
  if (begin == std::string::npos) {
    // Append at end (with a separating blank line).
    std::string out = original;
    if (!out.empty() && out.back() != '\n')
      out += '\n';
    if (!out.empty())
      out += '\n';
    out += newBlock;
    return out;
  }
  auto endMarkerPos = original.find(MARKER_END, begin);
  auto endLineEnd =
      (endMarkerPos == std::string::npos)
          ? original.size()
          : original.find('\n', endMarkerPos);
  if (endLineEnd == std::string::npos)
    endLineEnd = original.size();
  else if (endLineEnd < original.size())
    endLineEnd += 1;

  return original.substr(0, begin) + newBlock + original.substr(endLineEnd);
}

bool runHyprctlReload() {
  // Pipe so we can surface the output, which is useful if the config has
  // an unrelated syntax error.
  FILE *p = popen("hyprctl reload 2>&1", "r");
  if (!p)
    return false;
  char buf[256];
  while (std::fgets(buf, sizeof(buf), p)) {
    std::string s(buf);
    if (!s.empty() && s.back() == '\n')
      s.pop_back();
    std::cerr << "[hypr-sync] hyprctl: " << s << std::endl;
  }
  int rc = pclose(p);
  return rc == 0;
}

} // namespace

bool syncHyprlandBinds(const std::vector<ShortcutDescriptor> &shortcuts) {
  if (!isHyprland())
    return false;

  fs::path cfg = hyprlandConfigPath();
  if (cfg.empty()) {
    std::cerr << "[hypr-sync] HOME not set; cannot locate hyprland.conf."
              << std::endl;
    return false;
  }
  std::error_code ec;
  if (!fs::exists(cfg, ec)) {
    std::cerr << "[hypr-sync] No hyprland.conf at " << cfg
              << " — skipping auto-binds." << std::endl;
    return false;
  }

  // Read current content.
  std::string content;
  {
    std::ifstream in(cfg);
    if (!in) {
      std::cerr << "[hypr-sync] Cannot read " << cfg << std::endl;
      return false;
    }
    std::ostringstream ss;
    ss << in.rdbuf();
    content = ss.str();
  }

  const std::string newBlock = buildManagedBlock(shortcuts);
  const std::string updated = updateManagedBlock(content, newBlock);

  if (updated == content) {
    std::cerr << "[hypr-sync] hyprland.conf already matches the portal "
                 "shortcut set — nothing to do."
              << std::endl;
    return true;
  }

  // Atomic write: .saf-tmp sibling + rename().
  fs::path tmp = cfg;
  tmp += ".saf-tmp";
  {
    std::ofstream out(tmp, std::ios::binary | std::ios::trunc);
    if (!out) {
      std::cerr << "[hypr-sync] Cannot create " << tmp << std::endl;
      return false;
    }
    out << updated;
    out.flush();
    if (!out) {
      std::cerr << "[hypr-sync] Write to " << tmp << " failed." << std::endl;
      fs::remove(tmp, ec);
      return false;
    }
  }
  fs::rename(tmp, cfg, ec);
  if (ec) {
    std::cerr << "[hypr-sync] rename " << tmp << " -> " << cfg
              << " failed: " << ec.message() << std::endl;
    fs::remove(tmp, ec);
    return false;
  }

  std::cerr << "[hypr-sync] Updated " << cfg.string() << " with "
            << shortcuts.size() << " managed bind(s). Running hyprctl reload…"
            << std::endl;

  if (runHyprctlReload()) {
    std::cerr << "[hypr-sync] hyprctl reload OK — shortcuts are now live."
              << std::endl;
    return true;
  }
  std::cerr << "[hypr-sync] hyprctl reload failed. Run it manually if you "
               "want the new binds applied now."
            << std::endl;
  return false;
}

} // namespace saf
